name: preview/itsthecereal.life

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "apps/itsthecereal-life/**"
      - "packages/**"
env:
  PROJECT_SLUG: itsthecereal-life
  NODE_VERSION: 20

jobs:
  preview_itsthecereal-life:
    name: preview itsthecereal.life
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Clean install
        run: npm ci
      - name: Build
        run: npm run build -- --filter=${{ env.PROJECT_SLUG }}
      - name: Deploy preview
        uses: ./.github/actions/vercel
        with:
          working-directory: ./apps/${{ env.PROJECT_SLUG }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-scope: subhaze
          vercel-project: ${{ env.PROJECT_SLUG }}
          vercel-environment: preview
          node-version: ${{ env.NODE_VERSION }}
