name: production/itsthecereal-life

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "apps/itsthecereal-life/**"
      - "packages/**"
env:
  PROJECT_SLUG: itsthecereal-life
  NODE_VERSION: 20

jobs:
  production_itsthecereal-life:
    name: production itsthecereal-life
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Clean install
        run: npm ci
      - name: Build
        run: npm run build -- --filter=${{ env.PROJECT_SLUG }}
      - name: Deploy production
        uses: ./.github/actions/vercel
        with:
          working-directory: ./apps/${{ env.PROJECT_SLUG }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-scope: subhaze
          vercel-project: ${{ env.PROJECT_SLUG }}
          vercel-environment: production
          node-version: ${{ env.NODE_VERSION }}
          vercel-production-deploy: true
